export const ActionTypes = {
  MOVIES_LOADING: " MOVIES_LOADING",
  MOVIES_SUCCESS: "MOVIES_SUCCESS",
  MOVIES_ERROR: "MOVIES_ERROR",
  GENRES_LOADİNG: "GENRES_LOADİNG",
  GENRES_SUCCESS: "GENRES_SUCCESS",
  GENRES_ERROR: "GENRES_ERROR",
};
